### ISSUE TITLE
problem compiling with Visual Studio

### ISSUE THREAD

**Issue by peterritter** [nogden/xxsqlite#2]
Hello

First of all - thank you very much for this library! Looks nice! Just what I was looking for. I am working on a commercial project and I need to use sqlite for some tasks and I am not much of a low level c programmer. So this will help me keep things concise and clean!  
I assume that the Apache License does not affect the rest of the code in my project. I only need to keep your license text on your files intact and mention any changes I make, right? I spent half an hour googling  the apache license but I found it rather unclear because it sounded like I have to include the apache license in any source that includes/uses your code. I will just assume that this is not the case for now. 

I need to bulk insert very large quantities of records into a sqlite databases, so I need to do many inserts as part of a single transaction. It's a little bit unclear to me how I could achieve this with your library.

I had to disable a few things on Visual Studio like noexcept and '=default' probably because VS does not yet support this. However, one thing I was not able to fix was the following from database.cpp:

    void as_transaction(
        database& db,
        const std::function<void(database&)>& _operations
    ) {
        try {
            db.execute("BEGIN;");

            //NOT COMPILING!!
            //_operations(db);
            //NOT COMPILING!!

            db.execute("COMMIT;");
        } catch(...) {
            db.execute("ROLLBACK;");
            throw;
        }
    }

I'm not sure how to fix this for VS. It's unfortunate because it seems like this is really the only place in the library that deals with transactions. Do you have any ideas on an alternate way of implementing this?  

Many thanks, Peter

**Comment by nogden** [comment]
Hi Peter.

My apologies for the delay in my reply. The holiday season has been keeping me busy.

The Apache license should not affect any other code in your system. It is a permissive license that allows linking and redistribution at will. There is simply a requirement to keep the copyright headers and to distribute a copy of the license text with your application.

Obligatory disclaimer - I am not a lawyer and this should not be considered legal advice.

To perform many inserts as a transaction, you should create an iterable collection from your source data and then simply loop through the data performing all inserts inside the lambda function that you pass to `sqlite::as_transaction()`. This function will take care of making sure that all statements executed in the passed function are rolled up into the same transaction.
```
sqlite::as_transaction(db, [](sqlite::database &db) {  // ---
    for (auto item : src_data) {                       //  |
        db.execute("YOUR INSERT HERE");                //  | Everything here is in
        db.execute("ANOTHER INSERT");                  //  | the same transaction
    }                                                  //  |
});                                                    // ---
```
I know that Visual Studio 2010 doesn't have great support for lambda functions. It could be that you're running into an issue there. Unfortunately, I have neither Windows, nor Visual Studio available to test this. The only workaround that I can suggest, if indeed this is a compiler issue, is to manually issue `BEGIN` and `COMMIT` queries around your transactions.

**Comment by peterritter** [comment]
Hi Nick

thank you for your answer!. I have added a 'transaction class' to my
version here.  The destructor rolls back unless it was explicitly commited
before hand. This works on Visual Studio Could be an addition to your
library?

Best Regards, Peter Ritter


        transaction database::begin(void) {
            if(in_transaction())
                throw tsa::exception("sqlite::database",
                                     "Cannot begin new transaction. Already
in a transaction", SLOC);
            return transaction(this);
        }
        bool database::in_transaction(void)const {
            return !sqlite3_get_autocommit(m_db_ptr);
        }



        class transaction {
            friend class database;
            database* m_db_ptr = nullptr;
            bool m_is_open = true;
          public:
            transaction(database* db_ptr);
            transaction(const transaction&);
            ~transaction(void);
            void commit(void);
            void rollback(void);
        };
  transaction::transaction(database* db_ptr) {
            m_db_ptr = db_ptr;
            m_db_ptr->execute("BEGIN;");
        }

        transaction::transaction(const transaction& other) {
            m_db_ptr = other.m_db_ptr;
            tsa_assert(m_db_ptr);
            //other.m_db_ptr = nullptr;
        }

        transaction::~transaction(void) {
            rollback();
        }

        void transaction::commit(void) {
            if(m_is_open) {
                tsa_assert(m_db_ptr);
                m_db_ptr->commit();
            } else {
                throw std::exception(
                                     "Cannot commit transaction. Not a
valid transaction");
            }
            m_is_open = false;
        }

        void transaction::rollback(void) {
            if(m_is_open) {
                m_db_ptr->rollback();
            } else {
                //nothing
            }
            m_is_open = false;
        }
