### ISSUE TITLE
`make test` doesn't work

### ISSUE THREAD

**Issue by bithavoc** [nogden/xxsqlite#3]
Following Build Instructions:
> git clone git://github.com/nogden/xxsqlite.git
> cd xxsqlite
> mkdir build
> cd build
> cmake ..
> make
> make test

prints:

`make: *** No rule to make target 'test'.  Stop.`

OS: OSX Yosemite.

**Comment by nogden** [comment]
The tests depend upon gtest (Google Test) being available. Please ensure that this library is installed and found by CMake.
I'll add a note to the README clarifying this.

**Comment by bithavoc** [comment]
Ohh, so if It can't find the library then make doesn't generate 'test'?

**Comment by nogden** [comment]
Exactly. In that case CMake should output a message about not finding the GTest library and that the tests will not be built.
