### ISSUE TITLE
different definition of std::function

### ISSUE THREAD

**Issue by bithavoc** [nogden/xxsqlite#5]
This definition of `std::function` found in database.hpp is causing problems when you include `<functional`> and xxsqlite in the same project, IMHO we should `include <functional>` in that header.

This is the offending definition:

```c++
namespace std {
    template<class T> class function;
}   // namespace std
```

see here: https://github.com/nogden/xxsqlite/blob/master/src/database.hpp#L28

**Comment by nogden** [comment]
I've just pushed a commit making this change.

It turns out that opening the std namespace is not allowed anyway, so this way always an error. Thanks for reporting this.
